services:
  influxdb:
    image: influxdb:1.7-alpine
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=${INFLUXDB_DB:-k6}
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-k6}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD:-k6}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    healthcheck:
      test: "ln -sf /bin/busybox /bin/wget && /bin/wget -q -Y off http://localhost:8086/metrics -O /dev/null > /dev/null 2>&1"
      interval: 25s
      timeout: 3s
      start_period: 30s
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    networks:
      - monitoring


  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-dogpack}           # Grafana admin user
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-dogpackapp}   # Grafana admin password
      - GF_DATASOURCE_INFLUXDB_DB=${INFLUXDB_DB:-k6}           # Database name for InfluxDB 1.x
      - GF_DATASOURCE_INFLUXDB_USER=${INFLUXDB_USER:-k6}           # InfluxDB 1.x user
      - GF_DATASOURCE_INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-k6}    # InfluxDB 1.x user password
      - GF_DATASOURCE_INFLUXDB_URL=http://influxdb:8086        # InfluxDB URL
    volumes:
      - grafana-data:/var/lib/grafana
      - ./influxdb.yml:/etc/grafana/provisioning/datasources/influxdb.yml
    depends_on:
      - influxdb
    networks:
      - monitoring


  k6:
    build:
      context: ./k6
      dockerfile: Dockerfile
    environment:
      - K6_INFLUXDB_ADDR=http://influxdb:8086  # InfluxDB 1.x address
      - K6_INFLUXDB_DB=${INFLUXDB_DB:-k6}      # Database name
      - K6_INFLUXDB_USER=${INFLUXDB_USER:-k6}    # User for InfluxDB 1.x
      - K6_INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-k6} # User password
    volumes:
      - ./k6:/scripts
    # command: run /scripts/test.js -o xk6-influxdb
    command: run /scripts/test.js -o influxdb=http://influxdb:8086/k6
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - monitoring

volumes:
  influxdb-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
